name: sales_tracker
description: A Flutter application for tracking sales.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # //firebase_core: ^1.10.0
  # firebase_auth: ^3.11.2
  # cloud_firestore: ^3.1.7

  cupertino_icons: ^1.0.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
